### ISSUE TITLE
Deployment failed: Connection reset by peer (os error 104)

### ISSUE THREAD

**Issue by erfanium** [denoland/deploy_feedback#146]
I created a sample app with Deno Deploy and using MongoDB atlas for it's database.
source code: https://github.com/erfanium/deno-deploy-mongo
link: https://mongo-demo.deno.dev/

sometimes when I open the app after a while, it shows me `Deployment failed` page. refreshing the page solves the problem. here is my crash logs: 
```
ConnectionReset: Connection reset by peer (os error 104)     
at async read (deno:ext/net/01_net.js:21:19)     
at async BufReader.read (https://deno.land/std@0.118.0/io/buffer.ts:314:18)     
at async BufReader.readFull (https://deno.land/std@0.118.0/io/buffer.ts:343:28)     
at async WireProtocol.receive (https://deno.land/x/mongo@v0.29.0/src/protocol/protocol.ts:77:34)
```

I'm not sure that's a Deno Deploy problem, maybe that's a driver issue, but i'm sending it here because i only experienced this issue with Deno Deploy platform. I have no problem when I deploy my app on Docker based platforms.

**Comment by bnoordhuis** [comment]
"Connection reset by peer" means the other end closed the connection. Peers going away are a fact of life with TCP; it's the kind of runtime error you'll just have to handle.

I doubt Deploy is doing anything unusual, except that your deployments (and therefore your database connections) are probably longer-lived than they are on other platforms.

(That's not something you should rely on but Deploy is pretty good at keeping deployments around in order to minimize cold start times.)

**Comment by erfanium** [comment]
I added some debug lines to my code to figure out what's really going on. unfortunately this bug is not easily reproducible so i'll reopen this issue when I have more detail. 

Thank you! @bnoordhuis
