### ISSUE TITLE
Add a TODO App Template

### ISSUE THREAD

**Issue by guilt** [denoland/deploy_feedback#20]
It is often better to add a TODO list app, giving people pointers on how to write routes,
maybe connect to a persistent store; These things are the first things web developers
write when it comes to launching new applications for real world usecases.

**Comment by ChristianSiegert** [comment]
Have you checked the examples/documentation? Route handling boils down to checking `request.method` and `request.url` ([example 1](https://deno.com/deploy/docs/example-json), [example 2](https://deno.com/deploy/docs/example-post-request)). How to use a persistent store depends on the third-party service you use (documentation is usually provided by that service). Nevertheless, you’ll find two examples in the documentation ([example 1](https://deno.com/deploy/docs/tutorial-dynamodb), [example 2](https://deno.com/deploy/docs/tutorial-faunadb)).

**Comment by guilt** [comment]
Yes, I have. There isn't a generic way to make routing/route parameter handling easy, unless some amount of work goes in it; Plus, writing `request.method` checks isn't what a typical TODO app worries about. This is why I decided to raise this as an issue, so that route based code on deploy looks simple to write. If people wanted to use something like, say, MongoDB atlas or something else (see other tickets) they'd need to wait for the `connect` API to open up too. Hence, this could be looked at as a milestone ticket, once routing and generic DB capabilities are available.

**Comment by wperron** [comment]
The [FaunaDB](https://deno.com/deploy/docs/tutorial-faunadb) and [DynamoDB](https://deno.com/deploy/docs/tutorial-dynamodb) examples both use the [sift](https://github.com/satyarohith/sift) library which isn't "official" but that pretty much everyone has used internally and is very happy with. They also both provide examples of how to interact with two different types of databases. The examples aren't _exactly_ for a TODO app but I feel they can be easily adapted to suit that need. Some databases simply won't work at the moment due to the lack of support for outbound TCP connections required for MongoDB and most relational databases as well. We're working on these and will definitely add examples when they get supported.

> Hence, this could be looked at as a milestone ticket, once routing and generic DB capabilities are available.

I'm not sure what you mean exactly here? Do you have a more detailed example of something you would want to see in the docs that isn't currently there?

**Comment by satyarohith** [comment]
TODO examples:
- https://github.com/denoland/showcase_todo
- https://github.com/Atinux/nuxt-deno-kv
