### ISSUE TITLE
What Compile Error Blocked Deploy?

### ISSUE THREAD

**Issue by WardCunningham** [denoland/deploy_feedback#25]
When I push to master and didn't see my code deployed I thought Deno Deploy was broken.

I later discovered that a compile error silently blocked the deploy. Is there a better place to look next time this happens? Could there be a place that is hard to miss?

Aside: This happened while demoing your awesome product to a fellow engineer. I was stumped because my expectations were so high. He wasn't so encumbered, applied a little divide-and-conquer, found the mistake and remained impressed.

**Comment by lucacasonato** [comment]
Compile errors should result in the GitHub status showing a ❌  instead of a ✅ . The compile error message will be added as a comment to the commit. Here is an example:

https://github.com/lucacasonato/fetchevent_examples/commit/e15e6692fb5fc48eb330a836efbc4e9e516b0e72

![image](https://user-images.githubusercontent.com/7829205/116124203-48cb0e80-a6c4-11eb-9f89-35a93d12aa93.png)

In a PR this will show up inline in the PR view:

https://github.com/lucacasonato/fetchevent_examples/pull/3

![image](https://user-images.githubusercontent.com/7829205/116124504-ab240f00-a6c4-11eb-90ff-2a5d08e592d2.png)

Do you have specific ideas on how we can improve this?

**Comment by WardCunningham** [comment]
Overly confident in our cut-and-paste ability we went straight to the project page. The tip off that would have saved us is if an additional row were added to the __Preview Deployments__ table with an error message where one would expect a link to a deployment. With the commit linked right there I would have been fixing within seconds.

**Comment by ttogola** [comment]
@lucacasonato I ran into a case where the deploy failed but no error comment was added to the commit.

![image](https://user-images.githubusercontent.com/10608697/182636327-4f9dafe1-cd4c-4cef-8d9f-9efe6a0f157e.png)

Potentially relevant detail is that the repo is private? But in the Deno Deploy Github app everything seems to be configured correctly.

![image](https://user-images.githubusercontent.com/10608697/182637069-2b16df00-caec-492a-a7ce-14a59c16916d.png)

**Comment by ttogola** [comment]
Thanks for the quick reply. I can't read it fully because it gets truncated 😕 

![image](https://user-images.githubusercontent.com/10608697/182644758-6f3b661d-424e-4516-9ccd-f50d14e24f8e.png)

**Comment by arnauorriols** [comment]
Hi @WardCunningham and @ttogola, we have added failed deployments to the deployments list, together with the error message, and the ability to see the build logs of all deployments. All this will be available going forward for new deployments (no retrofitting). I believe this covers all the feedback provided in this issue, right? I'm closing now, but feel free to reopen if you want to elaborate further.
