### ISSUE TITLE
Unsupported APIs should not be available in the runtime

### ISSUE THREAD

**Issue by AnInternetTroll** [denoland/deploy_feedback#288]
Most unsupported APIs just don't exist. Examples of these are stable APIs such as `Deno.run` and `Deno.copy`, and unstable APIs such as `Deno.serve` and `Deno.createHttpClient`. 
There's also deprecated APIs such as `Deno.iter` and `Deno.writeAll` that don't exist either.

Unfortunately some APIs are not available yet still exist. Examples of these are `Deno.writeFile`/`Deno.writeFileSync`, `Deno.copyFile`/`Deno.copyFileSync`, `Deno.exit`, `Deno.kill`.

This leads to inconsistencies and it makes it harder to figure out if an API is supported or not, and it leads to bad code IMO. Such as checking for `typeof Deno.run === undefined`, which only works on deno deploy, instead of `(await Deno.permissions.query({ name: "run" })).state !== "granted"`, which works in the CLI as well.

Please consider removing these unsupported APIs from the runtime entirely.

**Comment by lucacasonato** [comment]
It is intentional that the APIs that do exist, exist. It is our intention that all stable APIs in Deno will exist in Deno Deploy too, in the limit. A user calling `Deno.run()` on Deno Deploy and receiving an error such as `PermissionDenied: running subprocesses is not permitted in this context` has a much better experience than a user that receives: `TypeError: undefined is not a function (calling Deno.run)`.

In the limit we want the Deno Deploy APIs to exactly mirror `deno run --allow-read=. --allow-env --allow-net main.ts`.

Any stable APIs that do not currently exist in Deno Deploy are not implemented either due to ecosystem compatibility issues (this is the case with `Deno.run`), or because they are deprecated (`Deno.copy` and friends).

You should not use checks such as `typeof Deno.run === undefined`. Instead use early permission checks (eg `(await Deno.permissions.query({ name: "run" })).state === "granted`, or handle `Deno.errors.PermissionDenied` errors in your code.
