### ISSUE TITLE
How to avoid Cold Starts?

### ISSUE THREAD

**Issue by l3onh4rd** [denoland/deploy_feedback#333]
Is there a possibility to avoid cold starts? So that the server is always up and running?

**Comment by lucacasonato** [comment]
Cold starts should be fast enough to be imperceptible. Do you have a deployment which takes a long time to cold start?

**Comment by l3onh4rd** [comment]
Alright, understood. Anyway is there a possibility to keep the server running. I push something into the repository and it deploys the current state and the server keeps running and alive until the next commit? Independent from what timeframe.

**Comment by l3onh4rd** [comment]
Anything planned in that direction? Or other options?

**Comment by lucacasonato** [comment]
What is your usecase?

**Comment by l3onh4rd** [comment]
I manage jwt tokens which are created depending on a key which is generated with the start of the server. With every restart (cold start) the key changes and all jwt tokes generated before are invalid. Which is a bit annoying but still workinh as long as one instance is up and running.

**Comment by An-GG** [comment]
hey @l3onh4rd , im currently facing a similar challenge, just wondering were you able to solve your use case? 

it seems like you dont necessarily want a Deploy instance that keeps running, you just want to avoid loosing the initial runtime state that was generated at deploy time so your key does not change.

is there a reason you cant store the key in something like Deno KV (or another persistent datastore)?

**Comment by l3onh4rd** [comment]
@An-GG Hi, thanks for your answer. Honestly I never faced that issue again. It was solved maybe with any update of Deno Deploy. I plan to use Deno KV for it. As I created this ticket Deno KV didn't even exist ;D

I think I close this issue.

**Comment by An-GG** [comment]
Ah ok. Interesting that you didn't encounter the issue again, I think past a certain usage frequency if the instance keeps running this is a non-issue, as you said. 

This is very long and unrelated but just in case you're curious:

For me it seems like after ~10 minutes of inactivity a new isolate is spun up and a key I define at the top level is regenerated. TLDR; I need this key to be generated only once when I click deploy, be shared across all the isolates/instances within a deployment, and I need this key to be stored in such a way that it cannot be retrieved / manipulated by anything other than the isolates running on the Deno Deploy platform which are part of that specific deployment (for ex. via connecting to KV externally with admin API keys). 

The idea is that if you publish your deployment publicly, users of the app can verify not just the app's code but also the integrity of the persistent state of the application throughout its lifetime without trusting the person who deployed it.
> **Edit:** I think versionstamps get us halfway there, but ideally even *reading* from the database is protected. That way, you could do something like collect and save sensitive user data without being able to read it, but still be able to use it in some other, hard-to-decentralize way that is critical to the functionality of your app. 

I asked about KV, not as a solution, but because it (and other ways to store things persistently across a deno deployment) are actually unsuitable for my use case and was wondering if you were avoiding this solution for the same reasons. Doesn't seem like thats the case and I'm glad things worked out.
