### ISSUE TITLE
Show some info about preview deployments if there's no production deployment

### ISSUE THREAD

**Issue by MrMarble** [denoland/deploy_feedback#396]
### Problem description

Deploying an empty project directly from the command line leaves de project in a "pending" status
![imagen](https://github.com/denoland/deploy_feedback/assets/4268580/e0a70896-f7ea-4b65-b96e-402a87593354)

```
deployctl deploy --project trending --token XXXX ./main.ts
√ Project: trending
i Uploading all files from the current dir (F:\repos\fresh)
√ Found 24 assets.
√ Uploaded 1 new asset.
√ Deployment complete.

View at:
 - https://trending-x1wt7r3fdb3g.deno.dev
```

Video: 
![video](https://github.com/denoland/deploy_feedback/assets/4268580/04cf99ac-963d-453a-8c96-54e4f70ac505)

### Steps to reproduce

1. Create a new project
2. Deploy some code from the cli

### Expected behavior

You can access the dashboard

### Additional context

Related to  #247

**Comment by ry** [comment]
I think this is because it doesn't have a production deployment yet. If you use `deployctl` with the `--prod` flag does it fix this?

**Comment by MrMarble** [comment]
> I think this is because it doesn't have a production deployment yet. If you use `deployctl` with the `--prod` flag does it fix this?

Yes, just tried it after posting the issue...
Maybe showing some info about the staging deployments would be nice. You have to have a production deployment to see the staging deployments

**Comment by Zhykos** [comment]
Hello. I have exactly the same issue: the project is still pending but my oak server is running.
Do you need some info?

**Comment by magurotuna** [comment]
FYI I updated the PR title to reflect the actual feature request.

**Comment by lucab** [comment]
The UI should now be fixed and properly showing projects which only contain preview deployments.
Additionally we just merged https://github.com/denoland/deployctl/pull/158 to slightly tweak `deployctl` behavior so that, on new empty projects, it initializes the production deployment on the very first push. And also better report production vs preview uploads.

All of this should hopefully result in less confusion when kickstarting a project using `deployctl`.
I'm closing this now, and thanks again for the report!
