### ISSUE TITLE
new option to deploy deno-ts apps

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deploy_feedback#43]
new options to deploy deno-ts apps
 the current option for the current deployment is good but I bring it closer to us puts constraints to write our deno-ts codes, that's why I like to have an option to deploy no import code deno-ts-  http functional locally with obviously the permissions that deno-deploy allows.  deno-deploy can have in addition to the code to execute certain data such as:
 - the version of the deno which must execute the code
 - the permissions required to execute the code, for that the deno-deploy web interface must allow these users to choose certain
 options such as allow-net, of course some authorization may not be available to all urilators for reasons such as allow-write
 - the command to be executed is:
 run <url to scipt> with the permissions already selected.
 the idea is to be able to remain functional api locally in deno-deploy without using docker or another hosting platform.

**Comment by lucacasonato** [comment]
> the version of the deno which must execute the code

Deno Deploy does not use the regular Deno CLI under the hood, so this doesn't work. Deno Deploy doesn't have a version at the moment - it supports features on a managed platform without backward incompatible changes.

> the permissions required to execute the code, for that the deno-deploy web interface must allow these users to choose certain
options such as allow-net, of course some authorization may not be available to all urilators for reasons such as allow-write

In the model of Deno CLI, Deno Deploy runs code witth the `--allow-net` and `--allow-env` permissions. There are no APIs available for FS operations, subprocesses, plugins or similar, so no permissions need to be available for those. Because Deno Deploy is assumed to run trusted code, we do not expose a way to disable permissions. If you desire this feature, please open a separate issue with a use case.

Because Deno Deploy is a managed platform for Deno scripts (and not arbitrary programs or Docker containers), we do not support specifying an entry point other than a Deno script.

**Comment by elycheikhsmail** [comment]
thank you for your clear feedback and responses
