### ISSUE TITLE
Malfunctioning size counter

### ISSUE THREAD

**Issue by rojvv** [denoland/deploy_feedback#456]
![image](https://github.com/denoland/deploy_feedback/assets/49933115/ec426829-24ee-4f74-9dd7-51d724791299)

Is all of that 0 bytes?

**Comment by lucab** [comment]
Thanks for the report. That indeed seems like a UI bug when showing DB statistics.

I did check a bunch of our own projects, and this does seem to affect only a subset of them.
We'll dig a bit more and try to find out what's the root-cause for those specific projects to show up as 0-size.
Just for reference, on which project are you seeing this? Do you maybe have some other KV-using projects where the size is properly reported instead?

**Comment by rojvv** [comment]
My project is soft-rook-16 (but don’t send requests to it, please). I don’t have other projects using KV.

**Comment by lucab** [comment]
The `Size` value which we are displaying is an estimate, and it turned out that for small DB sizes (< 3 MiB) it can be not completely accurate. In particular, under some circumstances the DB can return a 0-size estimate when the set of key-values is a small but non-empty.

We deployed some UI tweaks today which should fix this and avoid further confusion for users.
Thanks again for the feedback, and let us know if you see other inconsistent statistics.

**Comment by rojvv** [comment]
Looks much better now, thanks!
