### ISSUE TITLE
Deno.Command doesn't work but change log has it?

### ISSUE THREAD

**Issue by reggi** [denoland/deploy_feedback#457]
### What problem are you trying to solve?

This change log update from back in march list `Deno.Command` as an added native command for deno deploy but I'm seeing an error when I run with `.spawn` and `.output`. 

 https://deno.com/deploy/changelog#added-more-deno-apis

<img width="753" alt="Screen Shot 2023-07-28 at 11 47 53 AM" src="https://github.com/denoland/deploy_feedback/assets/296798/acc61fc0-2279-4648-b1d4-a6b03a9ef42e">

### Describe the solution you'd like

To use `Deno.Command` in deploy, ideally be able to stream things to `stdout` and from `stdin`. I got this working locally but trying it on Deno Deploy leads to an error.

### Describe alternatives you've considered

Not using Deno Deploy and rolling a server 😭

**Comment by reggi** [comment]
Oh let me guess, you can run `Deno.Command` but it can't be to run another `deno` process? 😬

**Comment by reggi** [comment]
The why -> https://github.com/dlemstra/magick-wasm/issues/106

**Comment by lucab** [comment]
Thanks for the report.
The changelog entry that you are referring shows some APIs that were recently added to Deploy in order to stay compatible with Deno public interface. This means you can now call/reference them without getting exceptions or undefined values, as it was previously happening because they weren't actually defined.

In general though, most operations are not allowed on Deploy because the platform doesn't expose a whole execution environment in the same way that a full OS does.
For example, in your case you cannot spawn other processes for arbitrary binaries, as the execution is constrained to whatever can be executed on the V8 runtime only.
