### ISSUE TITLE
Deno deploy: ISOLATE_INTERNAL_FAILURE

### ISSUE THREAD

**Issue by Pamel-a** [denoland/deploy_feedback#584]
I'm trying to deploy this [MongoDB][1] project

But on the deno deploy website I'm getting this error:
```js
Cloning repository (100%)
Project linked successfully. Building first deployment:
Downloaded
file:///src/config.js
Packaging complete
Error The deployment failed: ISOLATE_INTERNAL_FAILURE
```
I could not find much info about this error, I'd like to know if I'm doing something wrong in the imports or if it doesn't support Koa or Mongo?

  [1]: https://github.com/Pamel-a/mongo

**Comment by lucab** [comment]
Thanks for the report. Which project are you observing this failure on?

**Comment by Pamel-a** [comment]
> Thanks for the report. Which project are you observing this failure on?

Its in the first line of my report

**Comment by Pamel-a** [comment]
> Thanks for the report. Which project are you observing this failure on?

@lucab  It's in the first line of my report

It deployed, but when i make a request like `https://polite-parrot-52.deno.dev/api/vars/get` with the body `{"key": "test"}`
I am getting this error on **Logs**:
```js
gcp-southamerica-east1

  TimeoutError: ResourceRequest timed out
      at ResourceRequest._fireTimeout (file:///node_modules/.deno/generic-pool@3.7.1/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
      at Timeout.bound [as _onTimeout] (file:///node_modules/.deno/generic-pool@3.7.1/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
      at cb (ext:deno_node/internal/timers.mjs:63:31)
      at Object.action (ext:deno_web/02_timers.js:149:11)
      at handleTimerMacrotask (ext:deno_web/02_timers.js:63:10)
      at eventLoopTick (ext:core/01_core.js:189:21)
```
It doesnt even print the `console.log("get: ", key)` at [routes.js](https://github.com/Pamel-a/mongo/blob/main/routes.js)
Testing locally its working.

**Comment by Pamel-a** [comment]
@lucab  so, is this a deno issue?

**Comment by lucab** [comment]
Thanks for the additional details.
For what I can see on our end, the project `polite-parrot-52` is currently building and starting fine; it could be that the `ISOLATE_INTERNAL_FAILURE` your experienced was a transient glitch at the time.
From the logs you posted, it seems you are getting a runtime exception due to a timeout (possibly in the connection pool). I don't have specific knowledge about koa/mongo/your-project, but from a quick look I'd suggest you to double check all the bits and setup related to mongo.
I'm closing this ticket as there does not seem to be a persistent issue with `ISOLATE_INTERNAL_FAILURE` events.

**Comment by Pamel-a** [comment]
@lucab I'm pissed off, one week waiting to you come with this answer.

It is clearly a Deno issue, not "koa/mongo/your-project" 😒
That project is obviously just a small test to reproduce the bug. It **works** perfectly locally/ on Heroku

Did you even read the log?

![image](https://github.com/denoland/deploy_feedback/assets/142637979/a78eb353-6554-4737-ae7a-7022e8d780ec)

**Comment by lucab** [comment]
I'm sorry for that, however I'm not currently seeing evidence about the reported `ISOLATE_INTERNAL_FAILURE` problem, thus this specific ticket seems fine to be closed.

For the additional troubles you mentioned, I did see the logs you posted and also mentioned that they point to a runtime exception due to a connection timeout to your Mongo infrastructure.
I'm not directly identifying a problem on Deno Deploy side related to that, but I recommend that you further double-check your code (include dependencies) and infrastructure.
In particular, have a look at your DB setup and any stale library versions you may be using for problems like https://jira.mongodb.org/browse/NODE-5042. 

I'm locking this ticket now. If you identify a specific bug in Deno Deploy independently from your private DB setup or known driver bugs, feel free to open a new ticket with as many actionable details as needed.
Thanks again for you feedback.
