### ISSUE TITLE
[Bug]: "GitHub Action" is not available in Project Settings -> Git Integration

### ISSUE THREAD

**Issue by hiamani** [denoland/deploy_feedback#639]
### Problem description

While following [these instructions](https://docs.deno.com/deploy/manual/ci_github#github-action) I select my repository in `Project -> Settings -> Git Integration`. A selection between **Automatic** and **GitHub Action** is supposed to appear, but I don't see either, only an option to select a template and deploy the project (in what I assume is in **Automatic** mode).

### Steps to reproduce

1. Following [these instructions](https://docs.deno.com/deploy/manual/ci_github#github-action)
2. Link repository in `Project -> Settings -> Git Integration`
3. No option for **GitHub Action** appears

### Expected behavior

**GitHub Action** should appear in the integration options.

**Comment by magurotuna** [comment]
Thanks for the report. We have recently updated project creation flow and the corresponding doc isn't fully updated yet.

Essentially, the difference between "Automatic" and "GitHub Actions" has made opaque - the system sets up GitHub Actions workflow file if your deploy config requires it (for example, if build step is needed to deploy your project, then GitHub Actions mode will be chosen automatically), and otherwise doesn't.

We'll make sure to update the docs as soon as possible. In the meantime, feel free to post any additional questions you may have.

**Comment by magurotuna** [comment]
JFYI here's a draft version of doc update https://github.com/denoland/deno-docs/pull/373

**Comment by hiamani** [comment]
Thank you for the explanation! I'll close this issue :)
