### ISSUE TITLE
[Bug]: Deployment taking a long time

### ISSUE THREAD

**Issue by p3bozuric** [denoland/deploy_feedback#711]
### Problem description

I've set a GitHub project to deploy 18 hours ago, but it's still pending. Is this normal?

![image](https://github.com/user-attachments/assets/10bcd412-a4f9-4769-9dac-514262ac6fe8)

### Steps to reproduce

Steps as written in your documentation for deployment.

### Expected behavior

I expected it to already be deployed on my custom domain.

**Comment by igorbdl** [comment]
Resolved via support email.

For forked github repo's, the GitHub actions are disabled until the user goes to the Actions tab in the respective GitHub repository and accepts the risk to run them for a forked project.

Deno deploy GitHub Integration requires GitHub actions to be enabled so that the `.github/workflows/deploy.yaml` action can run and deploy the app.
