### ISSUE TITLE
[Bug]: "spent" versus "consumed" in setup - not sure if this is a bug but definitely confusing

### ISSUE THREAD

**Issue by nicosql** [denoland/deploy_feedback#715]
### Problem description

Hi guys

I just upgraded to pro and was going through the config, I literally have done nothing on the pro account other than delete some year old playgrounds so I am not sure if this a bug or not yet.  

Minimally I wanted to report this to say it is pretty confusing and would suggest 2 things:
- Better articulate (in text and via the progress bar) the difference between DOLLARS spent on the subscription to PRO and the CONSUMPTION of the allotted traffic beneath that $20 subscription.  Obviously I have already spent $20 but it doesn't make sense to me to represent it this way.
- **In case this is a bug:**: I want to make my spend limit the max that PRO offers monthly - but by doing so the UI and written language is telling me I have already hit my limit simply by signing up for PRO - therefore according to the visual I can accept no more request. :/   I hope that makes sense, image link below.     

https://app.screencast.com/Dkz5LcDHATVQi

### Steps to reproduce

1. sign up for Pro
2. Go to Setting for spend limit
3. set it to $20

### Expected behavior

It should be obvious that my consumption is Zero and that I have not consumed any bandwidth against my freshly minted pro subscription.  I would expect some better word choice to that effect (i.e. consumed versus spent and have progress bar not be FULL ON RED).

### Environment

MS Edge - Deno Deploy settings UI

### Possible solution

Change "Spent" to "consumed" and don't visually fill the meter red while also stating "once you hit the limit you stop receiving request"

or 

don't fill the meter as a function of dollars but rather consumption of allotted bandwidth.

### Additional context

I don't mean to be rude, the whole things is kind of odd - lol not sure if it's a bug or not.

I'm about to find out!

https://app.screencast.com/Dkz5LcDHATVQi

**Comment by arnauorriols** [comment]
The "Spent" indicator shows the amount of dollars already spent in the current billing month. In our opinion the word "consumed" would be less clear than "Spent" to communicate this. Keep in mind that there are various resources that are billed by usage: number of incoming requests, egress bandwith, kv read/writes, etc. We cannot refer to any particular one of them because the limit is not against any particular one of them, it's against the total amount of dollars spent. It could be nice to show them as additional information for sure, but the essential one is the dollars spent. 

If I understand correctly, what you are attempting to do is to avoid any extra cost besides the $20 pro subscription cost. While this is not the primary use case this feature is intended for, it's certainly valid. However as you found out setting a $20 spend limit automatically blocks any request to your projects, even if you still have the usage available free of extra charge. We'll look into preventing this from happening. Meanwhile, you can try setting a $20.01 limit. This will not get you the behaviour of the progress bar you expect (the progress bar shows dollars spent over dollar limit), but it will prevent your projects from getting blocked prematurely.

**Comment by nicosql** [comment]
fair enough - thank you for the quick response!
