### ISSUE TITLE
[Bug]: Deno deploy stuck at 100%

### ISSUE THREAD

**Issue by vicary** [denoland/deploy_feedback#747]
### Problem description

I am trying to deploy a Deno Fresh project into Deno Deploy, but the progress is stuck at 100% with no apparent reason.

1. `deployctl deploy` throws the error `error: TypeError: error reading a body from connection` after waiting for 5 minutes at `Deploying... (100.0%)`
2. The build logs at dash.deno.com is stuck at 100% \
   <img width="710" alt="image" src="https://github.com/user-attachments/assets/a84d13af-d877-41ab-9962-d609b8c3654a">

### Steps to reproduce

1. Clone the project
2. Run deno deploy

### Expected behavior

The deploy should succeed.

### Environment

- Deno version: 2.0.5
- OS: macOS 15.0.1 (24A348)
- deployctl version: 1.13.0

### Possible solution

N/A

### Additional context

Organization ID: 6d1d11f9-cd58-45bc-b2be-b56fef31bba3
Project URL: https://dash.deno.com/projects/azurefalcon

**Comment by vicary** [comment]
The deployments are passing again for some reason, closing this for no longer able to reproduce it.

**Comment by vicary** [comment]
This issue is happening again today, we are seeing timeout's where deploys stuck at 100%.

**Comment by magurotuna** [comment]
As far as we know, this issue happens if the project has many dependencies (especially npm modules), that needs to be resolved during build. In this case, the build process keeps going on in the background even after the build progress is stuck and deployctl times out, and it gets completed eventually.
Once a dependency is resolved in a build, subsequent builds can make use of cached results so it should be faster.
We need to make client messages on build logs less confusing as well as to speed up the dependency resolution, but in the meantime, retrying `deployctl deploy` some times will likely help.

**Comment by vicary** [comment]
@magurotuna Thanks for answering, retrying does eventually produce a successful deployment.

There is a slight difference for the failing deployments. They never finishes, instead, they disappear after stuck in the deployment list without a domain name for an hour or two. Deployments retried after they disappeared will succeed, probably because of cache reuse.

Which means we cannot assume an eventual successful deployment when we see timeout errors, CI/CD pipelines must keep retrying until succeed.
