### ISSUE TITLE
Can I run DynamoDB tutorial with deployctl?

### ISSUE THREAD

**Issue by kawarimidoll** [denoland/deploy_feedback#78]
I tryed DynamoDB tutorial (https://deno.com/deploy/docs/tutorial-dynamodb), and created gist (https://gist.github.com/kawarimidoll/2230d4bf701b80561b69badaea52dcd3/).
It works well on Deno Deploy, but can't start it with deployctl.

![Default__-zsh_](https://user-images.githubusercontent.com/8146876/128661230-c7d01cf0-ad99-4437-82c1-43004ed8b909.png)

```
❯ deployctl run --env=.env https://gist.githubusercontent.com/kawarimidoll/2230d4bf701b80561b69badaea52dcd3/raw/43d077b851423fa6a85fcb1e042b5c33bd524f83/dynamo_sample.js
error: Relative import path "@aws-sdk/types" not prefixed with / or ./ or ../ from "https://cdn.skypack.dev/-/@aws-sdk/smithy-client@v3.25.0-1TsnNZL4ee56yRTknh6t/dist=es2020,mode=types/dist/types/index.d.ts"
```

Same error occurred even if using local file with same contents.

![Default__-zsh_](https://user-images.githubusercontent.com/8146876/128661249-bb3f2864-9c55-4169-bcd2-1ac794f4e023.png)

How can I fix this?
Is there any difference between Deno Deploy and deployctl?

**Comment by wperron** [comment]
this seems to be more of an issue with Skypack than with Deno. From experience I know that their polyfilling doesn't always work 100%, I've had issues with the AWS SDK as well in the past. The last known good version for me was 3.12 if I recall correctly. You can try using a pinned version of the AWS SDK instead of implicitly using the latest version. On our end we'll take a look at the example in the docs and find a version that works well out of the box.

**Comment by kawarimidoll** [comment]
Thank you! It started correctly by specifying the version.
I tried some versions, v3.22.0 seems to be the latest version that works.

```diff ts
  import {
    DynamoDBClient,
    GetItemCommand,
    PutItemCommand,
- } from "https://cdn.skypack.dev/@aws-sdk/client-dynamodb?dts";
+ } from "https://cdn.skypack.dev/@aws-sdk/client-dynamodb@3.22.0?dts";
```

![screenshot](https://user-images.githubusercontent.com/8146876/128808378-0b72b6c3-5c70-46ca-bc01-e83f245cfbf2.png)
